version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=school
    ports:
      - "8000:8000"

  db:
    image: postgres:14.2
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data