# Generated by Django 4.0.1 on 2022-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm'),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birthdate', models.DateTimeField()),
                ('gender', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.DateTimeField()),
                ('imdb', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.ManyToManyField(to='movie.Actor')),
                ('movies', models.ManyToManyField(to='movie.Movie')),
            ],
        ),
    ]
