name: Netflix API CI

on:
  push:
    branches: [ latest_branch ]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_NAME: school
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: abd98100
        ports:
          - "5432:5432"
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: Netflix.settings
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
      run: |
          pip install -r requirements.txt
          pip install flake8
    - name: Install Requirements
      run: |
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests
      run: pytest
