name: Netflix API CI

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_NAME: school
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: abd98100
        ports:
          - "5432:5432"
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: Netflix.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest